# Generated by Django 6.0.2 on 2026-03-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('user', 'poll')},
        ),
    ]
