# Generated by Django 6.0.2 on 2026-04-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pollvote_unique_together'),
        ('core', '0005_user_account_type'),
    ]

    operations = [
    ]
