# Generated by Django 6.0.4 on 2026-04-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_poll_ended_posted_as_info'),
        ('core', '0005_poll_notification_flags'),
    ]

    operations = [
    ]
