# Generated by Django 6.0.2 on 2026-04-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260429_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='ended_posted_as_info',
        ),
        migrations.AddField(
            model_name='society',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('society_admin', 'Society Admin'), ('dev', 'Developer')], default='regular', max_length=20),
        ),
    ]
