"""Add image_url field to Society

Generated by patch.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='image_url',
            field=models.CharField(max_length=500, blank=True, default=''),
        ),
    ]
