# Generated by Django 6.0.2 on 2026-04-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_poll_ended_posted_as_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='notified_closing_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('poll_created', 'Poll Created'), ('poll_deleted', 'Poll Deleted'), ('poll_closing_soon', 'Poll Closing Soon'), ('review_liked', 'Review Liked')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poll')),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx')],
            },
        ),
    ]
